# Generated by Django 4.0.3 on 2022-03-15 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image_Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_tag_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Smug_Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=256)),
                ('business_owner', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=1024)),
                ('file_path', models.CharField(max_length=1024)),
                ('album_id', models.IntegerField(default=0)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('smug_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smugfolioapi.smug_users')),
            ],
        ),
        migrations.CreateModel(
            name='Image_Tag_Assignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smugfolioapi.images')),
                ('image_tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smugfolioapi.image_tags')),
            ],
        ),
    ]
