# Generated by Django 4.0.3 on 2022-03-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smugfolioapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='smug_user_id',
            new_name='smug_user',
        ),
        migrations.AddField(
            model_name='images',
            name='picture',
            field=models.ImageField(null=True, upload_to='smugimages'),
        ),
    ]
