# Generated by Django 4.0.3 on 2022-03-21 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smugfolioapi', '0004_alter_smug_users_business_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='image_tags',
            field=models.ManyToManyField(through='smugfolioapi.Image_Tag_Assignments', to='smugfolioapi.image_tags'),
        ),
    ]
